In [1]:
import os
os.getcwd()

'F:\\insofe data\\Rstudio\\lab30_3_2_18__page rank,clustering,navie bayes'

In [1]:
!pip install python_igraph-0.7.1.post6-cp35-none-win_amd64.whl

Requirement 'python_igraph-0.7.1.post6-cp35-none-win_amd64.whl' looks like a filename, but the file does not exist
python_igraph-0.7.1.post6-cp35-none-win_amd64.whl is not a supported wheel on this platform.


In [3]:
!pip install upgrade igraph

  Could not find a version that satisfies the requirement upgrade (from versions: )
No matching distribution found for upgrade
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [6]:
from igraph import Graph

In [41]:
# Introduction to Graphs
# Defining a graph
g = Graph(directed=True)
print(g)

IGRAPH D--- 0 0 --


In [8]:
# Adding vertices
g.add_vertices(3)
g.add_edges([(0,1), (1,2),(2,1)])
print(g)

IGRAPH U--- 3 3 --
+ edges:
0--1 1--2 1--2


In [9]:
# Adding some more vertices
g.add_vertices(3)
g.add_edges([(2,3),(3,4),(4,5),(5,3)])
print(g)# shows 6 vertices and 7 edges

IGRAPH U--- 6 7 --
+ edges:
0--1 1--2 1--2 2--3 3--4 4--5 3--5


In [11]:
#GET THE EDGE id
g.get_eid(2,3)
# remove the edge from graph
g.delete_edges(2,3)
print(g)

IGRAPH U--- 6 5 --
+ edges:
0--1 1--2 3--4 4--5 3--5


In [21]:
from igraph import *
g = Graph(directed=True)
g.add_vertices(3)
g.add_edges([(0,1),(1,0),(1,2),(2,0)])
g.write_svg("test1.svg")

In [15]:
# create a simple social nw
g = Graph([(0,1), (0,2), (2,3), (3,4), (4,2), (2,5), (5,0), (6,3), (5,6)])
# Assigning Attributes
g.vs["name"] = ["Alice", "Bob", "Claire", "Dennis", "Esther", "Frank", "George"]
g.vs["age"] = [25, 31, 18, 47, 22, 23, 50]
g.vs["gender"] = ["f", "m", "f", "m", "f", "m", "m"]
g.es["is_formal"] = [False, False, True, True, True, False, True, False, False]
print(g)

IGRAPH UN-- 7 9 --
+ attr: age (v), gender (v), name (v), is_formal (e)
+ edges (vertex names):
 Alice -- Bob, Claire, Frank             Esther -- Claire, Dennis
   Bob -- Alice                           Frank -- Alice, Claire, George
Claire -- Alice, Dennis, Esther, Frank   George -- Dennis, Frank
Dennis -- Claire, Esther, George


In [16]:
# get the degree of each person(no of inlink +outlink)
g.degree()
# get the edges from a vertex
print(g.degree("Alice"))
print(g.degree("Bob"))
print(g.degree(["Alice","Bob","Claire"]))

3
1
[3, 1, 4]


In [27]:
from igraph import *
g = Graph(directed=True)
g.add_vertices(3)
g.add_edges([(0,1),(1,0),(1,2),(2,0)])
print(g)

IGRAPH D--- 3 4 --
+ edges:
0->1 1->0 1->2 2->0


In [28]:
g.pagerank()

[0.3973996608253251, 0.3877897117015263, 0.21481062747314866]

# Compute page rank manually

In [32]:
import numpy as np
# input two matrices
mat1 = ([0, 1/2, 1],[1 ,0, 0],[0, 1/2, 0])
mat2 = ([1/3, 1/3, 1/3])
r1=np.dot(mat1,mat2)

In [33]:
r2=np.dot(mat1,r1)
print(r2)
r3=np.dot(mat1,r2)
print(r3)
r4=np.dot(mat1,r3)
print(r4)
r5=np.dot(mat1,r4)
print(r5)
r6=np.dot(mat1,r5)
print(r6)
r7=np.dot(mat1,r6)
print(r7)
r8=np.dot(mat1,r7)
print(r8)
r9=np.dot(mat1,r8)
print(r9)
r10=np.dot(mat1,r9)
print(r10)
r11=np.dot(mat1,r10)
print(r11)
r12=np.dot(mat1,r11)
print(r12)

[ 0.33333333  0.5         0.16666667]
[ 0.41666667  0.33333333  0.25      ]
[ 0.41666667  0.41666667  0.16666667]
[ 0.375       0.41666667  0.20833333]
[ 0.41666667  0.375       0.20833333]
[ 0.39583333  0.41666667  0.1875    ]
[ 0.39583333  0.39583333  0.20833333]
[ 0.40625     0.39583333  0.19791667]
[ 0.39583333  0.40625     0.19791667]
[ 0.40104167  0.39583333  0.203125  ]
[ 0.40104167  0.40104167  0.19791667]


In [49]:
r=mat2
for i in range(1,35):
    M=np.dot(mat1,r)
    r=M
    print(M)
G.pagerank()    

[ 0.5         0.33333333  0.16666667]
[ 0.33333333  0.5         0.16666667]
[ 0.41666667  0.33333333  0.25      ]
[ 0.41666667  0.41666667  0.16666667]
[ 0.375       0.41666667  0.20833333]
[ 0.41666667  0.375       0.20833333]
[ 0.39583333  0.41666667  0.1875    ]
[ 0.39583333  0.39583333  0.20833333]
[ 0.40625     0.39583333  0.19791667]
[ 0.39583333  0.40625     0.19791667]
[ 0.40104167  0.39583333  0.203125  ]
[ 0.40104167  0.40104167  0.19791667]
[ 0.3984375   0.40104167  0.20052083]
[ 0.40104167  0.3984375   0.20052083]
[ 0.39973958  0.40104167  0.19921875]
[ 0.39973958  0.39973958  0.20052083]
[ 0.40039062  0.39973958  0.19986979]
[ 0.39973958  0.40039062  0.19986979]
[ 0.4000651   0.39973958  0.20019531]
[ 0.4000651   0.4000651   0.19986979]
[ 0.39990234  0.4000651   0.20003255]
[ 0.4000651   0.39990234  0.20003255]
[ 0.39998372  0.4000651   0.19995117]
[ 0.39998372  0.39998372  0.20003255]
[ 0.40002441  0.39998372  0.19999186]
[ 0.39998372  0.40002441  0.19999186]
[ 0.40000407

[0.3973996608253251, 0.3877897117015263, 0.21481062747314866]

# Let us try to see the manual calculation we will use the formula
# (1-d)/N+d*(PR(Ti)/NO(Ti)+......+(PR(Tn)/NO(Tn))

In [23]:
#Round 1
# initial ranking of all page was .3333 which is equally distributed.
#page rank of page A, 
print((.15/3)+.85*((.333/2)+.333))
#page rank of B
print((.15/3)+.85*(.333))
#page rank of B
print((.15/3)+.85*(.333/2))

0.474575
0.33305
0.191525


In [11]:
#Round 2
#page rank of page A, 
print((.15/3)+.85*((0.33305/2)+0.191525))
#page rank of B
print((.15/3)+.85*(0.474575))
#page rank of B
print((.15/3)+.85*(0.33305/2))

0.3543425
0.45338875
0.19154625


In [12]:
#Round 3
#page rank of page A, 
print((.15/3)+.85*((0.45338875/2)+0.19154625))
#page rank of B
print((.15/3)+.85*(0.3543425))
#page rank of B
print((.15/3)+.85*(0.45338875/2))

0.40550453125
0.351191125
0.24269021875


In [13]:
#Round 4
#page rank of page A, 
print((.15/3)+.85*((0.351191125/2)+0.24269021875))
#page rank of B
print((.15/3)+.85*(0.40550453125))
#page rank of B
print((.15/3)+.85*(0.351191125/2))

0.405542914062
0.394678851562
0.199256228125


In [14]:
#Round 5
#page rank of page A, 
print((.15/3)+.85*((0.394678851562/2)+0.199256228125))
#page rank of B
print((.15/3)+.85*(0.405542914062))
#page rank of B
print((.15/3)+.85*(0.394678851562/2))

0.38710630582
0.394711476953
0.217738511914


In [15]:
#Round 6
#page rank of page A, 
print((.15/3)+.85*((0.394711476953/2)+0.217738511914))
#page rank of B
print((.15/3)+.85*(0.38710630582))
#page rank of B
print((.15/3)+.85*(0.394711476953/2))

0.402830112832
0.379040359947
0.217752377705


In [16]:
#Round 7
#page rank of page A, 
print((.15/3)+.85*((0.379040359947/2)+0.217752377705))
#page rank of B
print((.15/3)+.85*(0.402830112832))
#page rank of B
print((.15/3)+.85*(0.379040359947/2))

0.396181674027
0.392405595907
0.211092152977


In [17]:
#Round 8
#page rank of page A, 
print((.15/3)+.85*((0.392405595907/2)+0.211092152977))
#page rank of B
print((.15/3)+.85*(0.396181674027))
#page rank of B
print((.15/3)+.85*(0.392405595907/2))

0.396200708291
0.386754422923
0.21677237826


In [18]:
#Round 9
#page rank of page A, 
print((.15/3)+.85*((0.386754422923/2)+0.21677237826))
#page rank of B
print((.15/3)+.85*(0.396200708291))
#page rank of B
print((.15/3)+.85*(0.386754422923/2))

0.398627151263
0.386770602047
0.214370629742


In [19]:
#Round 10
#page rank of page A, 
print((.15/3)+.85*((0.386770602047/2)+0.214370629742))
#page rank of B
print((.15/3)+.85*(0.398627151263))
#page rank of B
print((.15/3)+.85*(0.386770602047/2))

0.396592541151
0.388833078574
0.21437750587


In [20]:
g.pagerank()

[0.3973996608253251, 0.3877897117015263, 0.21481062747314866]

# Example 2 Assignment

In [39]:
G1=Graph(directed=True)
G1.add_vertices(4)
G1.add_edges([(0,1),(0,2),(0,3),(1,0),(1,3),(2,0),(3,1),(3,2)])
print(G1)

IGRAPH D--- 4 8 --
+ edges:
0->1 0->2 0->3 1->0 1->3 2->0 3->1 3->2


In [40]:
G1.pagerank()

[0.32456140350877194,
 0.22514619883040934,
 0.22514619883040934,
 0.22514619883040932]